### ISSUE TITLE
RAVBA: Bug: Going to full-screen and back out again disables the overlay

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAEmus#64]
As in pressing ``pause/break`` twice.

The only way I could see to get the overlay back is to restart the emulator.

It's already understood that the overlay does not work in full-screen mode.

**Comment by Jamiras** [comment]
See also https://github.com/RetroAchievements/RAIntegration/issues/402

The window is destroyed and recreated when toggling to and from fullscreen.

**Comment by kdecks** [comment]
Seems this was already reported.
