### ISSUE TITLE
Security hole on RAP64

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAEmus#71]
You can get achievements by editing the memory if you use PJ64 built-in memory viewer, although is only on soft-core

**Comment by eldexterr** [comment]
Using the memory viewer from the debugger

**Comment by Jamiras** [comment]
All emulators allow built-in tools when not in hardcore mode. The memory viewer is just the tip of the iceberg, and PJ64 isn't the only one with a memory viewer. Some let you enter game genie codes. Others have built in cheat databases. Some even let you view the tile layout so you can see stuff offscreen, or toggle layer visibilities or effects like fog. Long ago, we make a decision that players can do whatever the emulator allows in non-hardcore mode. As long as that functionality is disabled in hardcore, everything is working as expected.

**Comment by eldexterr** [comment]
Oh didn't knew that, thanks for the clarification jamiras :)
In that case, case closed
