### ISSUE TITLE
Retroarch - Volume Randomly starts high pitch screeching sound only with RetroArch Emulators

### ISSUE THREAD

**Issue by thearchivalone** [RetroAchievements/RAEmus#78]
This is the second time this has happened when I was playing The Legend of Zelda and streaming my screen on Discrod. It scared the hell out of me both times. I was also streaming and running all audio through a software mixer (ASIOLINK).

Platform: Windows 10 x64
Emulator: RetroArch multiple cores
Game: Multiple games

Clip of the issue happening: https://clips.twitch.tv/GleamingConcernedPepperoniEleGiggle

**Comment by bedwardly-down** [comment]
Turns out it was my Audio Mixing Software not having a large enough audio buffer set for everything I was running. Not an Emu issue.

**Comment by meleu** [comment]
If it happened in RetroArch it should be reported in https://github.com/libretro/RetroArch/issues
And the steps to reproduce it would help a lot the debugging process.
